const Map<String, Map<String, List<String>>> kAllRolesAndSkillsByIndustry = {
  'software_engineering_it': {
    'Software Developer': ['Java', 'Python', 'JavaScript', 'React', 'Node.js', 'SQL', 'Git', 'HTML', 'CSS'],
    'Frontend Developer': ['HTML', 'CSS', 'JavaScript', 'TypeScript', 'React', 'Vue', 'Angular', 'TailwindCSS', 'Figma'],
    'Backend Developer': ['Node.js', 'Express', 'Python', 'Django', 'Go', 'PHP', 'Laravel', 'PostgreSQL', 'Redis', 'Docker'],
    'Full Stack Developer': ['MongoDB', 'Express', 'React', 'Node.js', 'Git', 'AWS', 'JavaScript', 'SQL', 'Docker'],
    'UI/UX Designer': ['Figma', 'Adobe XD', 'Photoshop', 'Wireframing', 'Prototyping', 'User Research', 'Sketch'],
    'QA Tester': ['Selenium', 'Jest', 'Postman', 'Cypress', 'JIRA', 'Manual Testing', 'Automation Testing'],
    'DevOps Engineer': ['Docker', 'Kubernetes', 'CI/CD', 'AWS', 'Linux', 'Terraform', 'Ansible', 'Git'],
    'Mobile App Developer': ['Flutter', 'Dart', 'React Native', 'iOS Development', 'Swift', 'Android Development', 'Kotlin'],
    'System Administrator': ['Linux', 'Windows Server', 'Active Directory', 'Networking', 'Shell Scripting', 'Virtualization'],
    'IT Support Specialist': ['Troubleshooting', 'Customer Service', 'Hardware Support', 'Operating Systems', 'Help Desk'],
  },
  'data_science_analytics': {
    'Data Analyst': ['Python', 'SQL', 'Excel', 'Tableau', 'Power BI', 'Data Visualization', 'Statistics'],
    'Data Scientist': ['Python', 'R', 'Machine Learning', 'SQL', 'Statistics', 'Pandas', 'NumPy', 'Jupyter'],
    'Machine Learning Engineer': ['Python', 'TensorFlow', 'PyTorch', 'Scikit-Learn', 'Deep Learning', 'Computer Vision', 'NLP'],
    'Data Engineer': ['SQL', 'Python', 'ETL Pipelines', 'Spark', 'Hadoop', 'Airflow', 'AWS', 'Databricks'],
    'BI Analyst': ['Power BI', 'Tableau', 'SQL', 'Data Warehousing', 'Business Intelligence', 'Dashboards'],
  },
  'design_ux_creative': {
    'Graphic Designer': ['Photoshop', 'Illustrator', 'InDesign', 'Branding', 'Typography', 'Logo Design', 'Vector Art'],
    'Video Editor': ['Premiere Pro', 'After Effects', 'Final Cut Pro', 'Video Production', 'Color Grading', 'Sound Design'],
    'Art Director': ['Creative Strategy', 'Concept Development', 'Team Leadership', 'Brand Identity', 'Adobe Creative Suite'],
    'Animator': ['3D Animation', '2D Animation', 'Blender', 'Maya', 'After Effects', 'Storyboarding', 'Character Design'],
    'Motion Designer': ['After Effects', 'Cinema 4D', 'Motion Graphics', 'Video Editing', 'Keyframing', 'Illustrator'],
  },
  'product_management': {
    'Product Manager': ['Product Roadmap', 'Agile/Scrum', 'JIRA', 'User Stories', 'Product Analytics', 'Market Research', 'SQL'],
    'Associate Product Manager': ['Agile', 'JIRA', 'User Research', 'Wireframing', 'Data Analysis', 'Product Backlog'],
    'Product Owner': ['Scrum Master', 'Product Backlog', 'Sprint Planning', 'Agile Methodologies', 'User Stories'],
    'Technical Product Manager': ['System Architecture', 'APIs', 'Product Strategy', 'Software Development Life Cycle (SDLC)', 'SQL'],
  },
  'sales_business_development': {
    'Sales Executive': ['Lead Generation', 'Communication', 'Negotiation', 'CRM (Salesforce/HubSpot)', 'Cold Calling', 'Sales Pitching'],
    'Business Development Executive': ['B2B Sales', 'Market Expansion', 'Client Acquisition', 'Relationship Management', 'Proposal Writing'],
    'Sales Manager': ['Sales Strategy', 'Team Leadership', 'Revenue Growth', 'Key Account Management', 'Forecasting'],
    'Key Account Manager': ['Client Relationship', 'Retention', 'Up-selling', 'Account Management', 'Negotiation'],
    'Inside Sales Representative': ['Lead Qualification', 'Telesales', 'CRM', 'Email Outreach', 'Product Demos'],
  },
  'marketing_digital_growth': {
    'Digital Marketing Specialist': ['SEO', 'SEM', 'Google Ads', 'Social Media Marketing', 'Email Marketing', 'Google Analytics'],
    'SEO Specialist': ['Search Engine Optimization', 'Google Search Console', 'Ahrefs', 'Keyword Research', 'Link Building', 'On-page SEO'],
    'Content Writer': ['Copywriting', 'SEO Writing', 'Blog Writing', 'Editing', 'Content Strategy', 'Creative Writing'],
    'Social Media Manager': ['Content Creation', 'Instagram/Facebook Ads', 'Buffer/Hootsuite', 'Community Management', 'Analytics'],
    'Growth Hacker': ['A/B Testing', 'Funnel Optimization', 'Conversion Rate Optimization (CRO)', 'Viral Marketing', 'Data Analytics'],
    'Brand Manager': ['Brand Strategy', 'Market Positioning', 'Advertising', 'Public Relations', 'Consumer Insights'],
  },
  'banking_finance': {
    'Financial Analyst': ['Financial Modeling', 'Valuation', 'Excel', 'Corporate Finance', 'Investment Analysis', 'Data Analysis'],
    'Investment Banker': ['M&A', 'Financial Analysis', 'Pitch Books', 'Due Diligence', 'Capital Markets', 'Valuation'],
    'Credit Analyst': ['Risk Assessment', 'Financial Statements', 'Credit Underwriting', 'Lending Analysis', 'Debt Structure'],
    'Loan Officer': ['Mortgage Lending', 'Customer Relations', 'Credit Analysis', 'Loan Documentation', 'Sales'],
    'Wealth Manager': ['Portfolio Management', 'Financial Planning', 'Asset Allocation', 'Relationship Management', 'Tax Planning'],
  },
  'accountants': {
    'Accountant': ['Tally Prime', 'GST Filing', 'Excel', 'Bookkeeping', 'Accounts Payable/Receivable', 'Bank Reconciliation'],
    'Chartered Accountant (CA)': ['Auditing', 'Taxation (Direct/Indirect)', 'Statutory Compliance', 'Financial Audits', 'Corporate Law'],
    'Tax Consultant': ['Income Tax Filing', 'GST Compliance', 'Tax Planning', 'Tax Law', 'Auditing'],
    'Bookkeeper': ['QuickBooks', 'Data Entry', 'Bank Reconciliation', 'Ledger Maintenance', 'Invoicing'],
    'Audit Associate': ['Internal Audit', 'External Audit', 'Compliance Checking', 'Vouching', 'Working Papers'],
  },
  'human_resources': {
    'HR Recruiter': ['Sourcing', 'Interviewing', 'Job Portals (Naukri/LinkedIn)', 'Applicant Tracking Systems (ATS)', 'Candidate Screening'],
    'HR Generalist': ['Employee Engagement', 'HR Policy Implementation', 'Performance Management', 'Onboarding', 'Grievance Handling'],
    'HR Manager': ['HR Strategy', 'Organizational Development', 'Talent Management', 'Labor Law', 'Budgeting'],
    'Talent Acquisition Specialist': ['Employer Branding', 'Executive Search', 'Headhunting', 'Recruiting Metrics', 'Negotiation'],
    'HR Operations Coordinator': ['Payroll Administration', 'Attendance Tracking', 'HRMS Tools', 'Documentation', 'Employee Database'],
  },
  'operations_logistics': {
    'Operations Coordinator': ['Process Optimization', 'Daily Operations', 'Coordination', 'Reporting', 'Problem Solving'],
    'Operations Manager': ['Strategic Planning', 'Resource Allocation', 'Budget Management', 'Process Improvement', 'KPI Tracking'],
    'Supply Chain Planner': ['Inventory Management', 'Demand Forecasting', 'Procurement', 'ERP Systems (SAP)', 'Material Requirements Planning (MRP)'],
    'Logistics Coordinator': ['Dispatching', 'Freight Management', 'Route Optimization', 'Tracking', 'Customs Clearance'],
    'Warehouse Supervisor': ['Inventory Counting', 'Safety Standards', 'Team Management', 'Stock Auditing', 'Shipping & Receiving'],
  },
  'healthcare_medical': {
    'Medical Practitioner / Doctor': ['Patient Diagnosis', 'Treatment Planning', 'Emergency Care', 'Medical Knowledge', 'Prescription Writing'],
    'Registered Nurse': ['Patient Monitoring', 'Medication Administration', 'Wound Care', 'ECG Monitoring', 'Compassion'],
    'Pharmacist': ['Dispensing Medicines', 'Inventory Control', 'Pharmacology Knowledge', 'Drug Interactions', 'Patient Counselling'],
    'Lab Technician': ['Blood Sample Processing', 'Microscopy', 'Laboratory Safety', 'Equipment Calibration', 'Pathology'],
    'Physiotherapist': ['Rehabilitation', 'Exercise Therapy', 'Manual Therapy', 'Pain Management', 'Patient Assessment'],
  },
  'education_training': {
    'Teacher / Lecturer': ['Classroom Management', 'Lesson Planning', 'Subject Matter Expertise', 'Student Evaluation', 'Presentation Skills'],
    'Online Tutor': ['E-learning Platforms (Zoom/Meet)', 'Interactive Teaching', 'Digital Whiteboards', 'Student Engagement'],
    'Instructional Designer': ['Curriculum Development', 'E-learning Authoring Tools (Articulate)', 'LMS Administration', 'Pedagogical Design'],
    'School Counselor': ['Student Counseling', 'Career Guidance', 'Behavioral Therapy', 'Parent Communication', 'Mental Health Support'],
    'Training Specialist': ['Corporate Training', 'Needs Analysis', 'Presentation Skills', 'Module Creation', 'Feedback Assessment'],
  },
  'legal_compliance': {
    'Legal Advisor': ['Legal Drafting', 'Corporate Governance', 'Legal Research', 'Contract Review', 'Arbitration & Litigation'],
    'Compliance Officer': ['Regulatory Compliance', 'Risk Assessment', 'Audit & Inspection', 'Policy Enforcement', 'Code of Conduct'],
    'Corporate Counsel': ['Mergers & Acquisitions', 'Commercial Contracts', 'Intellectual Property', 'Board Advising', 'Corporate Law'],
    'Paralegal': ['Case File Organization', 'Legal Research', 'Drafting Affidavits', 'Court Filing', 'Client Communication'],
    'Contract Specialist': ['Contract Drafting', 'Negotiation', 'Service Level Agreements (SLAs)', 'Contract Lifecycle Management', 'Risk Management'],
  },
  'customer_success_support': {
    'Customer Support Executive': ['Communication Skills', 'Ticket Management', 'Zendesk/Freshdesk', 'Customer Satisfaction (CSAT)', 'Active Listening'],
    'Customer Success Manager': ['Client Retention', 'Account Growth', 'Product Adoption', 'Onboarding', 'Customer Feedback Loop'],
    'Technical Support Specialist': ['Troubleshooting', 'API Testing', 'Network Diagnostics', 'Hardware/Software Installation', 'Bug Escalation'],
    'Helpdesk Representative': ['Call Handling', 'Data Entry', 'First Contact Resolution', 'Service Desk Tools (JIRA Service Management)'],
  },
  'manufacturing_engineering': {
    'Mechanical Engineer': ['AutoCAD', 'SolidWorks', 'CAD/CAM', 'Thermodynamics', 'Machine Design', 'FEA Analysis'],
    'Electrical Engineer': ['MATLAB', 'Circuit Design', 'PLC Programming', 'Power Systems', 'Electrical Safety Standards'],
    'Civil Engineer': ['STAAD Pro', 'Site Supervision', 'Estimation & Costing', 'Structural Analysis', 'Project Management'],
    'Production Engineer': ['Lean Manufacturing', 'Six Sigma', 'Assembly Line Management', 'Process Engineering', 'Safety Compliance'],
    'Quality Control Inspector': ['Quality Assurance Tools', 'Root Cause Analysis', 'Statistical Process Control (SPC)', 'ISO Standards Audit'],
  },
  'bpo_telecaller': {
    'Telecaller': ['Cold Calling', 'Lead Generation', 'Customer Engagement', 'Communication', 'Active Listening', 'Sales pitch'],
    'Customer Service Representative': ['Inbound Support', 'Conflict Resolution', 'Data Entry', 'CRM Handling', 'Escalation Procedures'],
    'Inbound Agent': ['Call Handling', 'Inquiry Resolution', 'Order Processing', 'Soft Skills', 'Product Knowledge'],
    'Outbound Agent': ['Sales Outcalls', 'Lead Qualifying', 'Appointment Scheduling', 'Handling Rejections', 'Telemarketing'],
    'Telemarketing Executive': ['Tele-sales', 'Target Orientation', 'Lead Tracking', 'Product Demos', 'Communication'],
  },
  'other_general': {
    'Administrative Assistant': ['Data Entry', 'Calendar Management', 'Office Administration', 'Email Correspondence', 'MS Office (Word/Excel)'],
    'Office Administrator': ['Vendor Coordination', 'Facility Management', 'Billing & Invoicing', 'Documentation', 'Supervision'],
    'Data Entry Operator': ['Typing Speed (WPM)', 'Data Accuracy', 'Excel Spreadsheet', 'Scanning & Archiving', 'Data Verification'],
    'Receptionist': ['Front Desk Operations', 'Visitor Management', 'Call Routing', 'Multitasking', 'Professional Etiquette'],
    'General Executive': ['Ad-hoc Tasks', 'Basic Report Preparation', 'Documentation', 'Time Management', 'Coordination'],
  },
  'bpo': {
    'BPO Executive': ['Customer Interaction', 'Data Entry', 'Voice & Non-voice Operations', 'Communication Skills', 'CRM Software'],
  },
  'telecaller': {
    'Telecaller Executive': ['Cold Calling', 'Lead Conversions', 'Customer Follow-up', 'Product Pitching', 'Communication'],
  },
  'banking': {
    'Bank Clerk': ['Cash Handling', 'Customer Service', 'Data Entry', 'Account Management', 'Basic Math'],
    'Branch Manager': ['Branch Operations', 'Team Leadership', 'Business Development', 'Compliance', 'Audit Oversight'],
  },
  'finance': {
    'Financial Advisor': ['Investment Planning', 'Risk Assessment', 'Mutual Funds', 'Client Relationship', 'Financial Planning'],
    'Treasury Analyst': ['Cash Management', 'Foreign Exchange', 'Liquidity Planning', 'Risk Mitigation', 'Financial Modeling'],
  },
  'retail_e_commerce': {
    'Retail Sales Associate': ['Customer Service', 'Cash Handling', 'Communication', 'Product Knowledge', 'Stocking', 'Up-selling'],
    'Store Manager': ['Team Leadership', 'Sales Management', 'Inventory Management', 'Store Operations', 'Customer Relations', 'Profit & Loss (P&L)'],
    'Cashier': ['Point of Sale (POS)', 'Cash Register', 'Accuracy', 'Basic Mathematics', 'Customer Service'],
    'Merchandiser': ['Visual Merchandising', 'Stock Analysis', 'Product Display', 'Retail Planning', 'Vendor Coordination'],
    'E-commerce Specialist': ['Shopify', 'Inventory Management', 'Order Processing', 'Online Sales', 'Customer Support', 'SEO'],
  },
  'hospitality_food': {
    'Hotel Manager': ['Guest Relations', 'Staff Supervision', 'Operations Management', 'Budgeting', 'Hospitality Standards'],
    'Receptionist / Front Desk': ['Check-in/Check-out', 'Phone Etiquette', 'Customer Service', 'Reservations Software', 'Multitasking'],
    'Travel Consultant': ['Itinerary Planning', 'Flight Bookings', 'Customer Service', 'Destination Knowledge', 'Sales'],
    'Chef / Cook': ['Culinary Skills', 'Food Safety', 'Menu Planning', 'Kitchen Management', 'Time Management'],
    'Waiter / Waitress': ['Table Service', 'Order Taking', 'Customer Relations', 'Active Listening', 'Food Safety'],
  },
  'delivery_driving': {
    'Delivery Rider': ['Two-wheeler License', 'Navigation (Google Maps)', 'Time Management', 'Package Handling', 'Local Area Knowledge'],
    'Driver (Car/Truck)': ['Valid License (LMV/HMV)', 'Safe Driving', 'Route Planning', 'Vehicle Maintenance', 'Punctuality'],
    'Courier Executive': ['Package Sorting', 'Delivery Tracking', 'Customer Verification', 'Mobile App Usage'],
    'Logistics Helper': ['Loading/Unloading', 'Physical Stamina', 'Warehouse Assistance', 'Package Labeling'],
  },
  'construction_real_estate': {
    'Real Estate Agent': ['Property Sales', 'Client Relationship', 'Negotiation', 'Market Analysis', 'Lead Generation', 'Contract Drafting'],
    'Site Engineer': ['Site Supervision', 'Civil Engineering', 'Project Scheduling', 'Quality Control', 'Safety Compliance'],
    'Architect': ['AutoCAD', '3D Modeling', 'Building Design', 'Client Presentations', 'Drafting'],
    'Electrician': ['Wiring', 'Electrical Repairs', 'Safety Standards', 'Circuit Diagnostics', 'Troubleshooting'],
    'Plumber': ['Plumbing Systems', 'Pipe Installation', 'Leak Repair', 'Sanitary Fitting', 'Blueprint Reading'],
  },
  'media_entertainment': {
    'Content Creator': ['Video Production', 'Content Strategy', 'Social Media Analytics', 'Scriptwriting', 'Canva', 'Creativity'],
    'Public Relations Executive': ['Press Releases', 'Media Relations', 'Crisis Management', 'Public Speaking', 'Event Planning'],
    'Photographer': ['Camera Operations', 'Lighting', 'Photo Editing (Lightroom)', 'Creativity', 'Client Directing'],
    'Social Media Influencer': ['Audience Engagement', 'Brand Collaborations', 'Video Editing', 'Niche Expertise'],
    'Journalist': ['Report Writing', 'Interviewing', 'Investigation', 'News Gathering', 'Fact Checking'],
  },
  'automotive': {
    'Auto Mechanic': ['Engine Diagnostics', 'Car Repair', 'Spare Parts', 'Hydraulics', 'Troubleshooting'],
    'Automobile Engineer': ['Vehicle Design', 'CAD Software', 'Automotive Systems', 'Testing & Prototyping'],
    'Service Advisor': ['Customer Service', 'Cost Estimation', 'Job Card Creation', 'Technical Explanations'],
    'Showroom Sales Executive': ['Automobile Sales', 'Customer Demos', 'Negotiation', 'Product Knowledge', 'Finance Coordination'],
  },
  'beauty_wellness': {
    'Beautician': ['Facial Treatments', 'Skincare', 'Waxing/Threading', 'Customer Relations', 'Salon Hygiene'],
    'Hair Stylist': ['Hair Cutting', 'Hair Coloring', 'Styling Techniques', 'Client Consultation', 'Product Sales'],
    'Makeup Artist': ['Bridal Makeup', 'Cosmetics Knowledge', 'Airbrush Makeup', 'Creativity', 'Color Theory'],
    'Spa Therapist': ['Massage Therapy', 'Anatomy Knowledge', 'Relaxation Techniques', 'Aromatherapy'],
    'Fitness Trainer': ['Personal Training', 'Diet Planning', 'Exercise Demonstration', 'Client Assessment', 'Motivation'],
  },
  'security_housekeeping': {
    'Security Guard': ['Patrolling', 'Access Control', 'Emergency Response', 'Physical Fitness', 'Report Writing'],
    'Housekeeper / Cleaner': ['Cleaning Standards', 'Chemical Handling', 'Room Maintenance', 'Attention to Detail'],
    'Facility Supervisor': ['Maintenance Coordination', 'Vendor Management', 'Security Supervision', 'Safety Auditing'],
    'Office Boy / Peon': ['Office Assistance', 'Tea/Coffee Service', 'Filing & Sorting', 'Errand Running'],
  }
};
